// HD basemap export via direct tile download and canvas composition.
//
// Produces a north-up PNG at a fixed target pixel width, independent of screen
// resolution and suitable for large-format printing.
//
// Algorithm:
//   1. Choose the tile zoom level so the bounds span ≈ targetWidth pixels.
//   2. Compute the exact pixel extent of the bounds in global tile space.
//   3. Determine the tile grid (xMin..xMax, yMin..yMax) covering those pixels.
//   4. Download all tiles in parallel (failed tiles are silently skipped).
//   5. Stitch tiles onto a scratch canvas.
//   6. Crop to the exact geographic bounds and return the canvas.

const TILE_SIZE = 256

// Pixel X coordinate (global tile space) for a longitude at zoom z.
function lngToPixelX(lng, z) {
  return (TILE_SIZE * 2 ** z * (lng + 180)) / 360
}

// Pixel Y coordinate (global tile space, top-left origin) for a latitude at zoom z.
// Web Mercator — matches the OSM/XYZ tile projection exactly.
function latToPixelY(lat, z) {
  const rad = (lat * Math.PI) / 180
  return (TILE_SIZE * 2 ** z * (1 - Math.log(Math.tan(rad) + 1 / Math.cos(rad)) / Math.PI)) / 2
}

// Replaces {z}, {x}, {y}, {s}, {r} in an XYZ URL template.
// Cycles through subdomains by tile position to distribute load.
function buildTileUrl(template, z, x, y, subdomains) {
  const sArr =
    Array.isArray(subdomains) && subdomains.length > 0
      ? subdomains
      : typeof subdomains === 'string' && subdomains.length > 0
        ? subdomains.split('')
        : ['']
  const s = sArr[(x + y) % sArr.length]
  return template
    .replace('{z}', z)
    .replace('{x}', x)
    .replace('{y}', y)
    .replace('{s}', s)
    .replace('{r}', '') // retina variant ignored — use standard tiles
}

// Loads one tile image. Resolves with null on network/decode error so that
// the overall export continues with a blank square for that tile.
function loadTile(url) {
  return new Promise((resolve) => {
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.onload = () => resolve(img)
    img.onerror = () => resolve(null)
    img.src = url
  })
}

/**
 * Downloads XYZ tiles covering `bounds` and stitches them into an HTMLCanvasElement
 * cropped to the exact geographic extent.
 *
 * The resulting canvas dimensions (width × height) are derived from the tile
 * projection at the chosen zoom, so they are consistent with Web Mercator and
 * will align perfectly with SVGs generated by projectToPixel() using the same bounds.
 *
 * @param {L.LatLngBounds} bounds       Geographic extent (Leaflet LatLngBounds).
 * @param {object}         basemap      Catalog entry — must have type:'xyz', url, subdomains, maxZoom.
 * @param {number}         targetWidth  Desired output pixel width (default 10000).
 * @returns {Promise<{canvas: HTMLCanvasElement, width: number, height: number}>}
 */
export async function buildBasemapHDCanvas(bounds, basemap, targetWidth = 10000) {
  if (!basemap || basemap.type !== 'xyz') {
    throw new Error('HD basemap export only supports XYZ tile sources')
  }

  const west = bounds.getWest()
  const east = bounds.getEast()
  const north = bounds.getNorth()
  const south = bounds.getSouth()

  // Choose the largest zoom where bounds pixel width ≤ targetWidth, capped at maxZoom.
  // Formula: pixelWidth = TILE_SIZE * 2^z * lngSpan / 360
  // Solving for z: z = log2(targetWidth * 360 / (TILE_SIZE * lngSpan))
  const maxZoom = basemap.maxZoom ?? 19
  const zRaw = Math.log2((targetWidth * 360) / (TILE_SIZE * (east - west)))
  const zoom = Math.min(Math.floor(zRaw), maxZoom)

  // Exact pixel bounds within global tile space at the chosen zoom.
  const xPixelMin = lngToPixelX(west, zoom)
  const xPixelMax = lngToPixelX(east, zoom)
  const yPixelMin = latToPixelY(north, zoom) // north = smaller y (top-left origin)
  const yPixelMax = latToPixelY(south, zoom) // south = larger y

  const hdWidth = Math.round(xPixelMax - xPixelMin)
  const hdHeight = Math.round(yPixelMax - yPixelMin)

  // Tile grid covering the pixel bounds (inclusive on both sides).
  const xTileMin = Math.floor(xPixelMin / TILE_SIZE)
  const xTileMax = Math.ceil(xPixelMax / TILE_SIZE) - 1
  const yTileMin = Math.floor(yPixelMin / TILE_SIZE)
  const yTileMax = Math.ceil(yPixelMax / TILE_SIZE) - 1

  // Pixel offset of the geographic bounds within the stitched tile canvas.
  const offsetX = Math.round(xPixelMin - xTileMin * TILE_SIZE)
  const offsetY = Math.round(yPixelMin - yTileMin * TILE_SIZE)

  // Download all tiles in parallel.
  const { subdomains = null } = basemap
  const tilePromises = []
  for (let ty = yTileMin; ty <= yTileMax; ty++) {
    for (let tx = xTileMin; tx <= xTileMax; tx++) {
      const url = buildTileUrl(basemap.url, zoom, tx, ty, subdomains)
      tilePromises.push(loadTile(url).then((img) => ({ img, tx, ty })))
    }
  }
  const tiles = await Promise.all(tilePromises)

  // Stitch tiles onto a scratch canvas.
  const stitchW = (xTileMax - xTileMin + 1) * TILE_SIZE
  const stitchH = (yTileMax - yTileMin + 1) * TILE_SIZE
  const stitchCanvas = document.createElement('canvas')
  stitchCanvas.width = stitchW
  stitchCanvas.height = stitchH
  const stitchCtx = stitchCanvas.getContext('2d')
  for (const { img, tx, ty } of tiles) {
    if (!img) continue
    stitchCtx.drawImage(img, (tx - xTileMin) * TILE_SIZE, (ty - yTileMin) * TILE_SIZE)
  }

  // Crop stitched canvas to the exact geographic bounds.
  const hdCanvas = document.createElement('canvas')
  hdCanvas.width = hdWidth
  hdCanvas.height = hdHeight
  const hdCtx = hdCanvas.getContext('2d')
  hdCtx.drawImage(stitchCanvas, offsetX, offsetY, hdWidth, hdHeight, 0, 0, hdWidth, hdHeight)

  return { canvas: hdCanvas, width: hdWidth, height: hdHeight }
}
